### ISSUE TITLE
UploadMesh() panics when calling C

### ISSUE THREAD

**Issue by Peternj42** [gen2brain/raylib-go#303]
Calling UploadMesh() causes a panic: "runtime error: cgo argument has Go pointer to unpinned Go pointer", similar to issue #263
```go
//in rmodels.go:

// UploadMesh - Upload vertex data into a VAO (if supported) and VBO
func UploadMesh(mesh *Mesh, dynamic bool) {
 	C.UploadMesh(mesh.cptr(), C.bool(dynamic)) // <-- panics at call to C.UploadMesh()
}
```
I was able to make it work by adding a C function that generates a mesh:
```C
Mesh GenMeshCustom(Vector3* vertices, unsigned short* indices, int vertexCount, int triCount)
{
	int indexCount = triCount * 3;

	Mesh mesh = { 0 };

	mesh.vertexCount = vertexCount;
	mesh.triangleCount = triCount;

	mesh.vertices = (float*)malloc(sizeof(float) * vertexCount * 3);
	mesh.colors = (char*)malloc(sizeof(unsigned char) * vertexCount * 4);
	mesh.indices = (short*)malloc(sizeof(unsigned short) * indexCount);

	Color color = WHITE;

	for (size_t i = 0; i < vertexCount; i++)
	{
		size_t vIndex = i * 3;
		mesh.vertices[vIndex] = vertices[i].x;
		mesh.vertices[vIndex + 1] = vertices[i].y;
		mesh.vertices[vIndex + 2] = vertices[i].z;

		size_t cIndex = i * 4;
		mesh.colors[cIndex] = color.r;
		mesh.colors[cIndex + 1] = color.g;
		mesh.colors[cIndex + 2] = color.b;
		mesh.colors[cIndex + 3] = color.a;
	}

	for (size_t i = 0; i < indexCount; i++) {
		mesh.indices[i] = indices[i];
	}

	UploadMesh(&mesh, false);

	return mesh;
}
```
and calling it from this binding:
```go
func GenMeshCustom(vertices []Vector3, indices []uint16) Mesh {
	cVertCount := (C.int)(len(vertices))
	cTriCount := (C.int)(len(indices) / 3)
	cVerts := (*C.Vector3)(unsafe.Pointer(&vertices[0]))
	cIndices := (*C.ushort)(unsafe.Pointer(&indices[0]))

	ret := C.GenMeshCustom(cVerts, cIndices, cVertCount, cTriCount)
	v := newMeshFromPointer(unsafe.Pointer(&ret))
	return v
}
```
This works for my purposes, but probably isn't a great general solution since it adds functions that aren't part of raylib originally. I can't figure out what it is about UploadMesh() that doesn't work for cgo. The other bindings that pass Meshes and Models such as LoadModelFromMesh() work just fine.

**Comment by Peternj42** [comment]
Thanks to some advice from the raylib discord, another solution is to use runtime.Pinner before the call to UploadMesh():
```go
    pinner := runtime.Pinner{}
    pinner.Pin(mesh.Vertices)
    pinner.Pin(mesh.Colors)
    pinner.Pin(mesh.Indices)
    //other mesh pointer fields also need to be pinned if used

    rl.UploadMesh(&mesh, false)

    pinner.Unpin()
```
This will allow the mesh to be successfully uploaded and drawn to the screen, but it will crash when you call UnloadMesh() because it is trying to free memory that was never allocated in C. The only solution I found so far was to call an alternate version of UnloadMesh() in C that unloads the VAO and VBOs from vram, but doesn't call free() on the members of the mesh struct:
```go
func UnloadMeshCustom(mesh *Mesh) {
	cMesh := mesh.cptr()
	C.UnloadMeshCustom(*cMesh)
}
```
```C
#include "raylib.h"
#include <stdlib.h>

#ifndef MAX_MESH_VERTEX_BUFFERS
    #define MAX_MESH_VERTEX_BUFFERS  7    // Maximum vertex buffers (VBO) per mesh
#endif

void UnloadMeshCustom(Mesh mesh)
{
    // Unload rlgl mesh vboId data
    rlUnloadVertexArray(mesh.vaoId);

    if (mesh.vboId != NULL) for (int i = 0; i < MAX_MESH_VERTEX_BUFFERS; i++) rlUnloadVertexBuffer(mesh.vboId[i]);
}
```
Kinda hacky but it works. Would it be worthwhile to add the pinner code into UploadMesh() so it can be used in the same way as the raylib examples?

**Comment by rocktavious** [comment]
@Peternj42 - there are 2 other past issues about this
https://github.com/gen2brain/raylib-go/issues/270
https://github.com/gen2brain/raylib-go/issues/263

It looks like there was never a true solution for this in this library but I also ran into this yesterday.  It feels like there should be a way to expose custom mesh generation safely.  If there is anything i can do to help let me know because i need this functionality too.

**Comment by Peternj42** [comment]
@rocktavious You can implement either of the two solutions above by adding the new functions to rmodels.go, but I agree there should be a way to incorporate this into the library, as the current UploadMesh() doesn't work, and you can't create meshes in code without it. Here's three possible options I've come up with:

1. Add a function GenerateMeshCustom() to rmodels.go that calls into C code and returns a copy of the mesh. The mesh is created in C-allocated memory, and can be freed with the existing UnloadMesh() function. This is the way the built-in GenMesh...() functions work. This is what my first solution above does, but it would need to be expanded to include the other mesh vertex attributes (texture, normals, etc.) to make it work for general use, and the number of arguments would probably get excessive, or you'd have to create multiple new functions.

2. Modify UploadMesh() to include the code that pins the fields of the mesh before calling C.UploadMesh(), similar to my second solution above. This would make mesh creation work the same as the original raylib example. In this case the mesh data is allocated in go-managed memory, so it would require creating a new UnloadMeshCustom() to unload custom meshes safely. This would probably be confusing for people as any meshes created by the built-in GenMesh...() functions would still need to use the existing UnloadMesh(). You would have to remember how you created each mesh and call the appropriate function to unload it. 

3. Re-implement all the existing GenMesh...() functions in go rather than passing the call to C. Then you can modify UploadMesh() and UnloadMesh() to internally pin the go-managed memory before calling C. This option keeps the user-facing API unchanged, but obviously it's a much bigger change overall.

I can create a PR if @gen2brain or others think one of these is worth implementing.

**Comment by rocktavious** [comment]
@Peternj42 so i tried my hand at making a wrapper around this data using the go 1.21 runtime.Pinner technique and it seems to work.  I'm able to press `u` to unload the mesh (i think) and then `q` to modify the data in place then `l` to load it up again.  Then `u` to unload, `w` to modify the data again and then `l` to load it up again.

What is unclear to me is if this is just creating more and more and more meshes in VRAM since the log lines are
```
INFO: VAO: [ID 4] Mesh uploaded successfully to VRAM (GPU)
INFO: VAO: [ID 5] Mesh uploaded successfully to VRAM (GPU)
INFO: VAO: [ID 6] Mesh uploaded successfully to VRAM (GPU)
```

Here is my code

```
package main

import (
	rl "github.com/gen2brain/raylib-go/raylib"
	"runtime"
)

type Data struct {
	pinner    runtime.Pinner
	IsLoaded  bool
	Vertices  []float32
	Normals   []float32
	TexCoords []float32
	Mesh      *rl.Mesh
}

func NewData() *Data {
	data := Data{
		Vertices:  []float32{},
		Normals:   []float32{},
		TexCoords: []float32{},
	}
	return &data
}

func (s *Data) Build() {
	s.Vertices = append(s.Vertices, []float32{0, 0, 0, 1, 0, 2, 2, 0, 0}...)
	s.Normals = append(s.Normals, []float32{0, 1, 0, 0, 1, 0, 0, 1, 0}...)
	s.TexCoords = append(s.TexCoords, []float32{0, 0, 0.5, 1, 1, 0}...)
}

func (s *Data) One() {
	s.Vertices[5] = 4
	s.Vertices[6] = 4
}

func (s *Data) Two() {
	s.Vertices[5] = 2
	s.Vertices[6] = 2
}

func (s *Data) Upload() {
	if s.IsLoaded {
		return
	}
	s.pinner.Pin(&s.Vertices[0])
	s.pinner.Pin(&s.Normals[0])
	s.pinner.Pin(&s.TexCoords[0])
	s.Mesh = &rl.Mesh{
		TriangleCount: 1,
		VertexCount:   3,
		Vertices:      &s.Vertices[0],
		Normals:       &s.Normals[0],
		Texcoords:     &s.TexCoords[0],
	}
	rl.UploadMesh(s.Mesh, true)
	s.IsLoaded = true
}

func (s *Data) Release() {
	s.pinner.Unpin()
	s.IsLoaded = false
}

func main() {
	rl.InitWindow(800, 450, "Test")
	defer rl.CloseWindow()

	data := NewData()
	data.Build()
	data.Upload()

	camera := rl.Camera3D{Position: rl.Vector3{X: 5, Y: 5, Z: 5}, Up: rl.Vector3{Y: 1}, Fovy: 45}

	for !rl.WindowShouldClose() {
		if rl.IsKeyDown(rl.KeyL) {
			data.Upload()
		}
		if rl.IsKeyDown(rl.KeyQ) {
			data.One()
		}
		if rl.IsKeyDown(rl.KeyW) {
			data.Two()
		}
		if rl.IsKeyDown(rl.KeyU) {
			data.Release()
		}

		rl.UpdateCamera(&camera, rl.CameraOrbital)

		rl.BeginDrawing()
		rl.ClearBackground(rl.RayWhite)

		rl.BeginMode3D(camera)
		if data.IsLoaded {
			rl.DrawMesh(*data.Mesh, rl.LoadMaterialDefault(), rl.MatrixIdentity())
		}
		rl.DrawGrid(10, 1)
		rl.EndMode3D()

		rl.EndDrawing()
	}

	data.Release()
}
```

**Comment by Peternj42** [comment]
@rocktavious - I believe you are correct. UploadMesh() sends the mesh data to the GPU, and regardless of what you do with Mesh struct in go, the data stays on the GPU until you call UnloadMesh(). Then you'll see this log message:
```
INFO: VAO: [ID 2] Unloaded vertex array data from VRAM (GPU)
```
Here's the catch - UnloadMesh() does two things internally: calls openGL to free the GPU memory (which will succeed and display the message above) and calls free() on the mesh struct fields to release the C-allocated memory (which will cause a crash, because in passing a pinned Mesh struct from go, memory was never allocated in C). Hence the need to create a modified version of UnloadMesh() for this to work. 

That's my understanding of it at least. I had never used runtime.Pinner before digging into this issue, so I don't know the details of how it works.

**Comment by rocktavious** [comment]
@Peternj42 - yep so i forked this library and modified the `UnloadMesh` C function to take in a "release" bool and updated the cgo binding as well to pass in the bool
```C
// Unload mesh from memory (RAM and VRAM)
void UnloadMesh(Mesh mesh, bool release)
{
    // Unload rlgl mesh vboId data
    rlUnloadVertexArray(mesh.vaoId);

    if (mesh.vboId != NULL) for (int i = 0; i < MAX_MESH_VERTEX_BUFFERS; i++) rlUnloadVertexBuffer(mesh.vboId[i]);
    if (release == true)
    {
        RL_FREE(mesh.vboId);

        RL_FREE(mesh.vertices);
        RL_FREE(mesh.texcoords);
        RL_FREE(mesh.normals);
        RL_FREE(mesh.colors);
        RL_FREE(mesh.tangents);
        RL_FREE(mesh.texcoords2);
        RL_FREE(mesh.indices);

        RL_FREE(mesh.animVertices);
        RL_FREE(mesh.animNormals);
        RL_FREE(mesh.boneWeights);
        RL_FREE(mesh.boneIds);
    }
}
```

Then i modified my code to
```go
func (s *Data) Release() {
	if s.IsLoaded == false {
		return
	}
	s.pinner.Unpin()
	rl.UnloadMesh(s.Mesh, false)
	s.IsLoaded = false
}
```

and now i get the same VAO index being reused.

```
INFO: VAO: [ID 2] Unloaded vertex array data from VRAM (GPU)
INFO: VAO: [ID 2] Mesh uploaded successfully to VRAM (GPU)
INFO: VAO: [ID 2] Unloaded vertex array data from VRAM (GPU)
INFO: VAO: [ID 2] Mesh uploaded successfully to VRAM (GPU)
INFO: VAO: [ID 2] Unloaded vertex array data from VRAM (GPU)
```

So i think we can definitively say `UploadMesh` and `UnloadMesh` are broken in the golang bindings and we need a fix.

**Comment by Peternj42** [comment]
Here's the best fix I think. Modify both UploadMesh() and UnloadMesh() bindings in rmodels.go as follows. This requires no changes to C code, doesn't change the API, and should work the same for custom meshes and those created with the built-in GenMesh...() functions. 
```go
// UploadMesh - Upload vertex data into a VAO (if supported) and VBO
func UploadMesh(mesh *Mesh, dynamic bool) {
	pinner := runtime.Pinner{}
	//Mesh pointer fields must be pinned to allow a Mesh pointer to be passed to C.UploadMesh() below
	//nil checks are required because Pin() will panic if passed nil
	if mesh.Vertices != nil {
		pinner.Pin(mesh.Vertices)
	}
	if mesh.Texcoords != nil {
		pinner.Pin(mesh.Texcoords)
	}
	if mesh.Texcoords2 != nil {
		pinner.Pin(mesh.Texcoords2)
	}
	if mesh.Normals != nil {
		pinner.Pin(mesh.Normals)
	}
	if mesh.Tangents != nil {
		pinner.Pin(mesh.Tangents)
	}
	if mesh.Colors != nil {
		pinner.Pin(mesh.Colors)
	}
	if mesh.Indices != nil {
		pinner.Pin(mesh.Indices)
	}
	if mesh.AnimVertices != nil {
		pinner.Pin(mesh.AnimVertices)
	}
	if mesh.AnimNormals != nil {
		pinner.Pin(mesh.AnimNormals)
	}
	if mesh.BoneIds != nil {
		pinner.Pin(mesh.BoneIds)
	}
	if mesh.BoneWeights != nil {
		pinner.Pin(mesh.BoneWeights)
	}
	//VboID of a new mesh should always be nil before uploading, but including this in case a mesh happens to have it set.
	if mesh.VboID != nil {
		pinner.Pin(mesh.VboID)
	}

	cMesh := mesh.cptr()
	C.UploadMesh(cMesh, C.bool(dynamic))

	pinner.Unpin()
}

// UnloadMesh - Unload mesh from memory (RAM and/or VRAM)
func UnloadMesh(mesh *Mesh) {
	//C.UnloadMesh() only needs to read the VaoID & VboID
	//passing a temporary struct with all other fields nil makes it safe for the C code to call free()
	tempMesh := Mesh{
		VaoID: mesh.VaoID,
		VboID: mesh.VboID,
	}
	cmesh := tempMesh.cptr()
	C.UnloadMesh(*cmesh)
}
```
UpdateMeshBuffer() is also necessary to modify uploaded mesh data, but doesn't currently have a binding. I haven't tried using it but it should probably be added as well.

**Comment by gen2brain** [comment]
@Peternj42 Thanks, can you send a PR?

**Comment by rocktavious** [comment]
@Peternj42 & @gen2brain  - I tested with only the above modified code in my fork and it appears to work with the below code and you can press `q` or `w` to modify the mesh data and see the results immediately.  🎉 
```go
package main

import (
	"fmt"
	rl "github.com/gen2brain/raylib-go/raylib"
)

type Data struct {
	IsLoaded  bool
	Vertices  []float32
	Normals   []float32
	TexCoords []float32
	Mesh      *rl.Mesh
}

func NewData() *Data {
	data := Data{
		Vertices:  []float32{},
		Normals:   []float32{},
		TexCoords: []float32{},
	}
	return &data
}

func (s *Data) Build() {
	s.Vertices = append(s.Vertices, []float32{0, 0, 0, 1, 0, 2, 2, 0, 0}...)
	s.Normals = append(s.Normals, []float32{0, 1, 0, 0, 1, 0, 0, 1, 0}...)
	s.TexCoords = append(s.TexCoords, []float32{0, 0, 0.5, 1, 1, 0}...)
}

func (s *Data) One() {
	s.Vertices[5] = 4
	s.Vertices[6] = 4
	s.Release()
	s.Upload()
}

func (s *Data) Two() {
	s.Vertices[5] = 2
	s.Vertices[6] = 2
	s.Release()
	s.Upload()
}

func (s *Data) Upload() {
	if s.IsLoaded {
		return
	}
	s.Mesh = &rl.Mesh{
		TriangleCount: 1,
		VertexCount:   3,
		Vertices:      &s.Vertices[0],
		Normals:       &s.Normals[0],
		Texcoords:     &s.TexCoords[0],
	}
	rl.UploadMesh(s.Mesh, true)
	s.IsLoaded = true
}

func (s *Data) Release() {
	if s.IsLoaded == false {
		return
	}
	rl.UnloadMesh(s.Mesh)
	s.IsLoaded = false
}

func main() {
	rl.InitWindow(800, 450, "Test")
	defer rl.CloseWindow()
	count := 0

	data := NewData()
	data.Build()
	data.Upload()

	camera := rl.Camera3D{Position: rl.Vector3{X: 5, Y: 5, Z: 5}, Up: rl.Vector3{Y: 1}, Fovy: 45}

	for !rl.WindowShouldClose() {
		if rl.IsKeyDown(rl.KeyL) {
			data.Upload()
		}
		if rl.IsKeyDown(rl.KeyQ) {
			data.One()
		}
		if rl.IsKeyDown(rl.KeyW) {
			data.Two()
		}
		if rl.IsKeyDown(rl.KeyU) {
			data.Release()
		}
		if rl.IsKeyDown(rl.KeyS) {
			fmt.Println(count)
			data.Release()
			data.Upload()
			count++
		}

		rl.UpdateCamera(&camera, rl.CameraOrbital)

		rl.BeginDrawing()
		rl.ClearBackground(rl.RayWhite)

		rl.BeginMode3D(camera)

		rl.DrawMesh(*data.Mesh, rl.LoadMaterialDefault(), rl.MatrixIdentity())

		rl.DrawGrid(10, 1)
		rl.EndMode3D()

		rl.EndDrawing()
	}

	data.Release()

}
```

**Comment by unklnik** [comment]
@rocktavious My knowledge of C and this kind of thing is very lacking so can't offer any help.

**Comment by gen2brain** [comment]
Fix is merged, note that with this change Go 1.21 is required.

**Comment by JupiterRider** [comment]
```golang
cubeMesh := rl.GenMeshCube(100, 100, 100)
rl.UploadMesh(&cubeMesh, false)
```
Will result in:
`panic: runtime error: runtime.Pinner.Pin: argument is not a Go pointer`

**Comment by Peternj42** [comment]
@JupiterRider `GenMeshCube()` calls `UploadMesh()` internally, so you don't need to call Upload separately. You only need to use `UploadMesh()` if you created the Mesh struct manually in your go code.

**Comment by Peternj42** [comment]
@gen2brain & @rocktavious On second look there's still an issue with my solution for `UnloadMesh()` - it will cause a memory leak when used with meshes created from `GenMesh...()` as their fields are allocated in C and won't get freed. I think we'll just have to create a separate function for custom meshes:
```go
// UnloadMesh - Unload mesh from memory (RAM and/or VRAM).
// Use this function to unload meshes created with Raylib's built-in GenMesh...() functions.
// To unload a custom mesh use UnloadMeshCustom().
func UnloadMesh(mesh *Mesh) {
	cmesh := mesh.cptr()
	C.UnloadMesh(*cmesh)
}

// UnloadMeshCustom - Unload mesh from VRAM only.
// Use this function to unload custom meshes uploaded with UploadMesh().
func UnloadMeshCustom(mesh *Mesh) {
	//C.UnloadMesh() only needs to read the VaoID & VboID to unload mesh from VRAM
	//passing a temporary struct with all other fields nil makes it safe for the C code to call free()
	tempMesh := Mesh{
		VaoID: mesh.VaoID,
		VboID: mesh.VboID,
	}
	cmesh := tempMesh.cptr()
	C.UnloadMesh(*cmesh)
}
```
Not quite as clean a solution but with the added comments it should be clear which one to call. Thoughts?

**Comment by gen2brain** [comment]
@Peternj42 I prefer to avoid custom functions like that, even if nicely commented it creates confusion for the users, i.e. when to use what, I guess it would be the source of many future issues, and it differs from the way Raylib handles it.

The main question seems to be how can we differentiate the mesh allocated in C vs the one allocated in Go.

Your suggestion to "Re-implement all the existing GenMesh...() functions in go rather than passing the call to C." now sounds nice, but not sure how complicated that would be. And it also makes maintenance much more difficult.

**Comment by gen2brain** [comment]
@rocktavious The Size of the struct should be the same as in C, that is why some structs have some padding defined. It will probably create some problems, not sure what C code expects.

**Comment by Peternj42** [comment]
@gen2brain & @rocktavious the error that JupiterRider posted suggests that `runtime.Pinner` can detect the difference between c and go pointers in the Mesh struct. Maybe we can take advantage of that? I'll experiment with it and see.

**Comment by Peternj42** [comment]
@gen2brain & @rocktavious After looking into it, the `runtime` package doesn't export any of the functions it uses internally to check the pointer value. I was able to come up with a workaround that attempts to pin the mesh and captures the panic if it happens: 
```go
func IsGoManagedMesh(mesh Mesh) bool {
	isGoManagedMesh := true
	defer func() {
		if err := recover(); err != nil {
			errString, ok := err.(string)
			if ok && errString == "runtime.Pinner.Pin: argument is not a Go pointer" {
				isGoManagedMesh = false
				return
			}
		}
	}()
	pinner := runtime.Pinner{}
	pinner.Pin(mesh.Vertices) //this will panic if not a Go pointer

	pinner.Unpin()
	return isGoManagedMesh
}
```
As you can see this is quite hacky and fragile, relying on an exact string comparison, but it does work in this simple test:
```go
	meshCube = rl.GenMeshCube(10, 10, 10)
	meshPlane = rl.GenMeshPlane(100, 100, 10, 10)
	meshCustom = genMesh(customVerts, indices, rl.White) //mesh created in go and uploaded via UploadMesh()

	fmt.Println(rl.IsGoManagedMesh(meshCube))
	fmt.Println(rl.IsGoManagedMesh(meshPlane))
	fmt.Println(rl.IsGoManagedMesh(meshCustom))
```
Output:
```
INFO: VAO: [ID 2] Mesh uploaded successfully to VRAM (GPU)
INFO: VAO: [ID 3] Mesh uploaded successfully to VRAM (GPU)
INFO: VAO: [ID 4] Mesh uploaded successfully to VRAM (GPU)
false
false
true
```

**Comment by JupiterRider** [comment]
I would prefer implementing these functions in raylib-go ...
```c
RLAPI void *MemAlloc(unsigned int size);                          // Internal memory allocator
RLAPI void *MemRealloc(void *ptr, unsigned int size);             // Internal memory reallocator
RLAPI void MemFree(void *ptr);                                    // Internal memory free
```
... and then maybe add getter- and setter-methods to the Mesh struct.

Something like this:
```golang
func (m *Mesh) SetVertices(vertices []float32) {

}
```

**Comment by Peternj42** [comment]
@gen2brain & @rocktavious Here's another approach - store a list of mesh VaoIDs created from calls to `UploadMesh()`, then check the list in `UnloadMesh()`:
```go
// slice to store VaoIDs
var goManagedMeshIDs []uint32 = make([]uint32,0)

// UploadMesh - Upload vertex data into a VAO (if supported) and VBO
func UploadMesh(mesh *Mesh, dynamic bool) {       

        ...

	cMesh := mesh.cptr()
	C.UploadMesh(cMesh, C.bool(dynamic))


	goManagedMeshIDs = append(goManagedMeshIDs, mesh.VaoID)

	pinner.Unpin()
}

// UnloadMesh - Unload mesh from memory (RAM and/or VRAM).
func UnloadMesh(mesh *Mesh) {
	if slices.Contains(goManagedMeshIDs, mesh.VaoID) {
		tempMesh := Mesh{
			VaoID: mesh.VaoID,
			VboID: mesh.VboID,
		}
		cmesh := tempMesh.cptr()
		C.UnloadMesh(*cmesh)
		goManagedMeshIDs = slices.DeleteFunc(goManagedMeshIDs, func(id uint32) bool {return id == mesh.VaoID})
	} else {
		cmesh := mesh.cptr()
		C.UnloadMesh(*cmesh)
	}
}

**Comment by gen2brain** [comment]
@Peternj42 Yes, that one looks much nicer, and I guess would be good enough. Btw. I added the `UpdateMeshBuffer`.

**Comment by Peternj42** [comment]
@gen2brain Sounds good, posted PR #307 for it.
